# Generated by Django 4.2.7 on 2024-01-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('job_seeker', '0002_job_seeker_birth_date_job_seeker_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
