# Generated by Django 4.2.7 on 2024-01-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('job_seeker', '0003_alter_job_seeker_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_seeker',
            name='country',
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='country',
            field=models.ManyToManyField(to='location.location'),
        ),
    ]
