# Generated by Django 4.2.7 on 2024-01-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0004_remove_job_seeker_country_job_seeker_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_seeker',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='street_address',
        ),
    ]
