# Generated by Django 4.2.7 on 2024-02-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_alter_job_seeker_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker',
            name='resume',
            field=models.TextField(default=''),
        ),
    ]
