# Generated by Django 4.2.7 on 2024-02-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0007_alter_job_seeker_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_seeker',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='resume',
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='CareerObjective',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='Contact',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='Experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='about_me',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='github_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='others_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='projects_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='skills',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('csharp', 'C#'), ('php', 'PHP'), ('ruby', 'Ruby'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('swift', 'Swift'), ('typescript', 'TypeScript'), ('reactjs', 'React.js'), ('angular', 'Angular'), ('nodejs', 'Node.js'), ('django', 'Django'), ('flask', 'Flask'), ('laravel', 'Laravel'), ('spring', 'Spring'), ('android', 'Android'), ('ios', 'iOS'), ('unity', 'Unity'), ('unreal', 'Unreal Engine'), ('git', 'Git')], max_length=50, null=True),
        ),
    ]
