# Generated by Django 4.2.7 on 2024-01-16 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_user'),
        ('jobs', '0002_jobs_industry_jobs_location_alter_jobs_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='posted_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
