# Generated by Django 4.2.7 on 2024-01-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobs_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Job_type',
            field=models.CharField(choices=[('Full Time', 'full_time'), ('Part-Time', 'part_time'), ('Remote', 'Remote')], default='Full Time', max_length=30),
        ),
    ]
