# Generated by Django 4.2.7 on 2024-01-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Benifits',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='jobs',
            name='Post',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='jobs',
            name='Responsibities',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='jobs',
            name='qualifications',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
