# Generated by Django 4.2.7 on 2024-02-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0011_remove_job_seeker_skills_job_seeker_skills'),
        ('jobs', '0007_remove_jobapplication_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.ManyToManyField(to='job_seeker.skill'),
        ),
    ]
