# Generated by Django 4.2.7 on 2024-01-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='industry',
        ),
    ]
