# Generated by Django 4.2.7 on 2024-04-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Company_Logo',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
    ]
